apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: gateway
  labels:
    version: "v8-bad"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gateway
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 20s }
        - analysis:
            templates:
              - templateName: gateway-error-rate
            args:
              - name: canary-hash
                valueFrom:
                  podTemplateHashValue: Latest
        - setWeight: 50
        - pause: { duration: 20s }
        - setWeight: 100
  template:
    metadata:
      labels:
        app: gateway
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: gateway
      terminationGracePeriodSeconds: 40
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: gateway
          image: ghcr.io/kostya2505/quickticket-gateway:7855e0d4bb79c8c68faacda0161c617b1b3985f2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: EVENTS_URL
            value: "http://broken-on-purpose:8081"
          - name: GATEWAY_TIMEOUT_MS
            value: "2000"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 1
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080